### ISSUE TITLE
收益颇丰

### ISSUE THREAD

**Issue by smallflowers** [shuaicj/http-proxy-netty#1]
最近有个项目是做http代理的，刚接触netty，有很多不懂的地方，看完代码受益颇丰

但是有个问题想请教一下；
我刚开始实现的时候，客户端bootstrap是单独创建的，没有放在messageReceived里面，想复用bootstrap
，通过服务端的handler构造函数把bootstrap注入， 然后在服务端handler的messageReceived中，调用bootstrap的connect方法，来连接远程服务器，不知道我这中方式有什么问题

**Comment by shuaicj** [comment]
正确使用的情况下Bootstrap是支持多次调用connect的。
